### PR TITLE
Add When snippet

### PR DESCRIPTION
**Pull request by thastings3**
This add the `When/when` snippet options

### CODE REVIEW

**Comment by MissingRoberto** [comment]
@onsi can you merge & publish this, please?

**Comment by onsi** [comment]
dump - thanks for the bump!

**Comment by onsi** [comment]
hmm - i’m gonna have to set up my dev environment to publish the plugin.  will try to get to it in the next few days.

**Comment by MissingRoberto** [comment]
Thank you @onsi!

**Pull request merged**
